# Generated by Django 5.1.3 on 2024-11-07 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveIntegerField()),
                ('lesson_desc', models.TextField()),
                ('grade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('id_stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good_job.student')),
                ('id_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good_job.subject')),
            ],
        ),
    ]
